blueprint:
  name: Prueba plantilla 2
  description: Inicia recordatorio de toma de medicación a través de Alexa e informa al cuidador si se la ha tomado o no 
  domain: automation
  input:
    mqtt_topic:
      name: Topic mqtt
      description: El topic de mqtt al que se suscribe
      default: ""
      
    mqtt_payload:
      name: Payload mqtt
      description: El payload que debe recibir par iniciar la automatización
      default: ""
        
    notify_device:
      name: Notification
      description: Device needs to run the official Home Assistant app to receive notifications
      selector:
        device:
          integration: mobile_app
          multiple: false

    input_boolean:
      name: Dedicated input_boolean
      description: Create and set here a input_boolean to handle history and state of the automation
      selector:
        entity:
          domain: input_boolean
          multiple: false

    notification_title_1:
      name: Notification title taken(Optional)
      description: "Default: Medication taken"
      default: "Medication taken"

    notification_message_1:
      name: Notification message (Optional)
      description: "Default: El usuario 1 se ha tomado la medicación"
      default: "El usuario 1 se ha tomado la medicación"

    notification_title_2:
      name: Notification title not taken(Optional)
      description: "Default: Medication not taken"
      default: "Medication not taken"

    notification_message_2:
      name: Notification message (Optional)
      description: "Default: El usuario 1 NO se ha tomado la medicación"
      default: "El usuario 1 NO se ha tomado la medicación"

    ask_later_wait_time:
      name: Wait time before next reminder
      description: Minutes before notify again after a Ask later action.
      default: 30
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: minutes
          step: 1
          mode: slider

    alexa_device:
      name: Dispositivo Alexa
      description: Elige el dispositivo Alexa para notificar al usuario
      selector:
        device:
          integration: alexa_media
          multiple: false

trigger:
  - platform: mqtt
    topic: !input mqtt_topic
    payload: !input mqtt_payload
    
action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: !input input_boolean
      
  - service: notify.alexa_media
    data:
      target: !input alexa_device
      message: Hora de tomarse la medicación
      data:
        type: tts
